# Generated by Django 2.2.6 on 2019-10-26 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighbourhood_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighbourhood_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Neighbourhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighbourhood_name', models.CharField(max_length=100)),
                ('neighbourhood_location', models.CharField(max_length=100)),
                ('occupants', models.IntegerField(blank=True)),
                ('founded_on', models.DateField(auto_now_add=True)),
                ('neighbourhood_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='NWatch.Admin')),
            ],
        ),
    ]
