# Generated by Django 2.2.6 on 2019-10-26 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NWatch', '0002_business_occupant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='default.jpg', upload_to='profile/')),
                ('bio', models.TextField()),
                ('phone_number', models.IntegerField(blank=True, default='0700000000')),
                ('plot_number', models.CharField(max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HealthContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
                ('department_phone_number', models.IntegerField()),
                ('department_address', models.CharField(blank=True, max_length=50)),
                ('department_email', models.EmailField(blank=True, max_length=254)),
                ('neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_details', to='NWatch.Neighbourhood')),
            ],
        ),
    ]
