# Generated by Django 2.2.6 on 2019-10-26 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NWatch', '0003_healthcontact_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcontact',
            name='neighbourhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_details', to='NWatch.Neighbourhood'),
        ),
        migrations.CreateModel(
            name='SecurityContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
                ('department_phone_number', models.IntegerField()),
                ('department_address', models.CharField(blank=True, max_length=50)),
                ('department_email', models.EmailField(blank=True, max_length=254)),
                ('neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_details', to='NWatch.Neighbourhood')),
            ],
        ),
    ]
