# Generated by Django 2.2.6 on 2019-10-26 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NWatch', '0004_auto_20191026_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcontact',
            name='neighbourhood',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_details', to='NWatch.Neighbourhood'),
        ),
        migrations.AlterField(
            model_name='securitycontact',
            name='neighbourhood',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_details', to='NWatch.Neighbourhood'),
        ),
    ]
