# Generated by Django 2.2.6 on 2019-10-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NWatch', '0005_auto_20191026_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_hood',
            field=models.BooleanField(default=True, help_text='Is your business in the same neighbourhood you are in'),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(help_text='Your business name', max_length=100),
        ),
    ]
