# Generated by Django 2.2.6 on 2019-10-27 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NWatch', '0006_auto_20191027_0931'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HealthContact',
            new_name='Health',
        ),
        migrations.RenameModel(
            old_name='SecurityContact',
            new_name='Security',
        ),
    ]
