# Generated by Django 2.2.6 on 2019-10-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NWatch', '0008_neighbourhood_hood_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='health',
            old_name='department_address',
            new_name='Health_center_address',
        ),
        migrations.RenameField(
            model_name='health',
            old_name='department_email',
            new_name='Health_center_email',
        ),
        migrations.RenameField(
            model_name='health',
            old_name='department_name',
            new_name='Health_center_name',
        ),
        migrations.RenameField(
            model_name='health',
            old_name='department_phone_number',
            new_name='Health_center_phone_number',
        ),
        migrations.RenameField(
            model_name='security',
            old_name='department_email',
            new_name='Police_station_email',
        ),
        migrations.RenameField(
            model_name='security',
            old_name='department_name',
            new_name='Police_station_name',
        ),
        migrations.RenameField(
            model_name='security',
            old_name='department_phone_number',
            new_name='Police_station_phone_number',
        ),
        migrations.RemoveField(
            model_name='security',
            name='department_address',
        ),
        migrations.AddField(
            model_name='security',
            name='Police_station_address',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
