# Generated by Django 2.2.6 on 2019-10-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NWatch', '0010_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
